# This is a basic workflow to help you get started with Actions

name: 编译OpenWRT

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: 查询CPU信息
        run: |
          echo $(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c)

      # Runs a set of commands using the runners shell
      - name: 克隆openwrt,回退至v22.03.0
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git&& cd openwrt&&git branch newBranch 17bd6b04777d71d081ddf4ff8fbf44ccaf6f422e &&git checkout newBranch
      - name: 更新软件包
        run: cd openwrt&&./scripts/feeds update -a
      - name: 安装所有包
        run: cd openwrt&&./scripts/feeds install -a
      - name: 进行编译配置
        run: cd openwrt&&cp -a ../ax6s.config .config&&make defconfig
      - name: 下载依赖
        run: cd openwrt&&make download -j$(nproc) V=s
      - name: 编译固件
        run: cd openwrt&&make -j$(nproc) V=s
      - name: Upload firmware to WeTransfer
        run: |
          cd openwrt
          curl -fsSL git.io/file-transfer | sh
          ./transfer -s -p ${FIRMWARE} 
        
